### ISSUE TITLE
Login - As a user I want to login to my salesforce account

### ISSUE THREAD

**Issue by PrineelB** [TrueSparrowSystems/AI-SalesSparrow-iOS-App#3]
[Figma here](https://www.figma.com/file/LybBhjLQAfZYM2qiVgFeU4/SalesBridge?type=design&node-id=1000-41768&mode=design&t=WJUAfV6iITf0KQs7-4)

As a user, I need to see my Salesforce Accounts details to prepare for the calls - Primary requisite for this is to connect the Salesforce account with SaleSparrow so all the data can be populated.

**Comment by alpeshvmodi** [comment]
iOS Task - #13

**Comment by AMAN-BARBARIA** [comment]
We do not need to include the following as a part of user story and there can be a separate user story for them: 
1. Disconnect Feature - https://github.com/TrueSparrowSystems/AI-SalesSparrow-API/issues/9
2. Logout from Other Devices Endpoint - https://github.com/TrueSparrowSystems/AI-SalesSparrow-API/issues/14
